// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpmpOjuYz8bE_i-6PgY_r9bdtE0B0-Lc',
    appId: '1:925653057177:web:e9b085749accdaa0f14208',
    messagingSenderId: '925653057177',
    projectId: 'expense-manager-app-ea7ee',
    authDomain: 'expense-manager-app-ea7ee.firebaseapp.com',
    storageBucket: 'expense-manager-app-ea7ee.firebasestorage.app',
    measurementId: 'G-ZRHF42R7S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuUuKeakxHE7tiinhq5m2cFSc0CPKHlRI',
    appId: '1:925653057177:android:49813716e0c83a5af14208',
    messagingSenderId: '925653057177',
    projectId: 'expense-manager-app-ea7ee',
    storageBucket: 'expense-manager-app-ea7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDxrx2TD1UFQJccGgKUxxIfj1F0L7ooc',
    appId: '1:925653057177:ios:c40c31c8075d7706f14208',
    messagingSenderId: '925653057177',
    projectId: 'expense-manager-app-ea7ee',
    storageBucket: 'expense-manager-app-ea7ee.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWDxrx2TD1UFQJccGgKUxxIfj1F0L7ooc',
    appId: '1:925653057177:ios:c40c31c8075d7706f14208',
    messagingSenderId: '925653057177',
    projectId: 'expense-manager-app-ea7ee',
    storageBucket: 'expense-manager-app-ea7ee.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGpmpOjuYz8bE_i-6PgY_r9bdtE0B0-Lc',
    appId: '1:925653057177:web:5418d19eb313a944f14208',
    messagingSenderId: '925653057177',
    projectId: 'expense-manager-app-ea7ee',
    authDomain: 'expense-manager-app-ea7ee.firebaseapp.com',
    storageBucket: 'expense-manager-app-ea7ee.firebasestorage.app',
    measurementId: 'G-DMHWMYZFH9',
  );
}
